INSERT INTO USERS (CLIENT_ID, USER_NAME, USER_PASSWORD,RFID_CODE) VALUES (1, 'fran', '123','04 D8 16 8E 1E 56 81');
INSERT INTO USERS (CLIENT_ID, USER_NAME, USER_PASSWORD,RFID_CODE) VALUES (2, 'Luis', '123','04 D8 16 8E 1E 56 82');
INSERT INTO HOMES (ID,CITY,LOCATION,NUMBER,CP,CLIENT_ID) VALUES(5,'Almería','Calle Almería',5,04004,1);
INSERT INTO HOMES (ID,CITY,LOCATION,NUMBER,CP,CLIENT_ID) VALUES(2,'Almería','Avenida Nuestra Señora de Montserrat',47,04004,1);
INSERT INTO HOMES (ID,CITY,LOCATION,NUMBER,CP,CLIENT_ID) VALUES(3,'Almería','Calle El Greco',5,04004,2);